apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  destination:
    namespace: external-dns
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.23.0
    chart: external-dns
    helm:
      releaseName: external-dns
      values: |
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
