apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mem0
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mem0
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/manifests/mem0
    repoURL: "https://github.com/timmyb824/homelab-kubernetes-apps.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
