apiVersion: v1
kind: Secret
metadata:
  name: adguard-configuration
  namespace: external-dns
type: Opaque
stringData:
  url: https://adguard.local.timmybtech.com
  user: <path:secret/data/homepage#ADGUARD_USER>
  password: <path:secret/data/homepage#ADGUARD_PASSWORD>
